"use client";

import { AppShell } from "@/components/AppShell";
import { ChatBot } from "@/components/copilot/ChatBot";
import { 
  mockKpis, 
  lenderVolumeData, 
  turnTimeTrendData 
} from "@/data/mockData";
import { 
  BarChart, 
  Bar, 
  XAxis, 
  YAxis, 
  CartesianGrid, 
  Tooltip, 
  Legend, 
  ResponsiveContainer, 
  LineChart, 
  Line 
} from "recharts";

export default function AdminOverviewPage() {
  return (
    <AppShell>
      <div className="hero-banner">
        <h1 className="hero-banner-title" style={{ fontSize: 24, fontWeight: 800, marginBottom: 8 }}>
          Executive Overview
        </h1>
        <p className="hero-banner-muted">
          Real-time metrics across all lenders and appraisers
        </p>
      </div>

      <div className="kpi-grid">
        <div className="kpi-card">
          <div className="kpi-label">Active Lenders</div>
          <div className="kpi-value">12</div>
          <div className="kpi-trend up">+2 this month</div>
        </div>
        <div className="kpi-card">
          <div className="kpi-label">Total Orders</div>
          <div className="kpi-value">{mockKpis.activeOrders}</div>
          <div className="kpi-trend up">+18% this week</div>
        </div>
        <div className="kpi-card">
          <div className="kpi-label">Total Borrower Savings</div>
          <div className="kpi-value" style={{ color: "var(--accent)" }}>
            ${mockKpis.totalBorrowerSavings.toLocaleString()}
          </div>
          <div className="kpi-trend up">+24% YoY</div>
        </div>
        <div className="kpi-card">
          <div className="kpi-label">Avg Turn Time</div>
          <div className="kpi-value">{mockKpis.avgTurnTimeDays} days</div>
          <div className="kpi-trend up">-1.2 days</div>
        </div>
      </div>

      <div className="grid-2" style={{ marginTop: "24px" }}>
        <div className="card">
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 16, color: "var(--text)" }}>
            Order Volume by Lender
          </h3>
          <div style={{ height: 250 }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={lenderVolumeData} layout="vertical">
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                <XAxis 
                  type="number" 
                  stroke="var(--muted)" 
                  tick={{ fontSize: 12 }} 
                />
                <YAxis 
                  dataKey="name" 
                  type="category" 
                  stroke="var(--muted)" 
                  tick={{ fontSize: 11 }} 
                  width={100} 
                />
                <Tooltip 
                  contentStyle={{ 
                    background: "var(--card)", 
                    border: "1px solid var(--border)", 
                    borderRadius: 8 
                  }} 
                />
                <Bar 
                  dataKey="orders" 
                  fill="var(--accent)" 
                  radius={[0, 8, 8, 0]} 
                />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="card">
          <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 16, color: "var(--text)" }}>
            Platform-wide Turn Time Trend
          </h3>
          <div style={{ height: 250 }}>
            <ResponsiveContainer width="100%" height="100%">
              <LineChart data={turnTimeTrendData}>
                <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
                <XAxis 
                  dataKey="month" 
                  stroke="var(--muted)" 
                  tick={{ fontSize: 12 }} 
                />
                <YAxis 
                  stroke="var(--muted)" 
                  tick={{ fontSize: 12 }} 
                  domain={[5, 9]} 
                />
                <Tooltip 
                  contentStyle={{ 
                    background: "var(--card)", 
                    border: "1px solid var(--border)", 
                    borderRadius: 8 
                  }} 
                  formatter={(value) => [`${value ?? 0} days`, "Avg Turn Time"]} 
                />
                <Line 
                  type="monotone" 
                  dataKey="avgDays" 
                  stroke="#8b5cf6" 
                  strokeWidth={3} 
                  dot={{ fill: "#8b5cf6", r: 5 }} 
                  activeDot={{ r: 8 }} 
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      <div className="card" style={{ marginTop: "16px" }}>
        <h3 style={{ fontSize: 16, fontWeight: 700, marginBottom: 16, color: "var(--text)" }}>
          Savings Generated by Lender
        </h3>
        <div style={{ height: 250 }}>
          <ResponsiveContainer width="100%" height="100%">
            <BarChart data={lenderVolumeData}>
              <CartesianGrid strokeDasharray="3 3" stroke="var(--border)" />
              <XAxis 
                dataKey="name" 
                stroke="var(--muted)" 
                tick={{ fontSize: 11 }} 
              />
              <YAxis 
                stroke="var(--muted)" 
                tick={{ fontSize: 12 }} 
                tickFormatter={(value) => `$${((value ?? 0) / 1000).toFixed(0)}k`} 
              />
              <Tooltip 
                contentStyle={{ 
                  background: "var(--card)", 
                  border: "1px solid var(--border)", 
                  borderRadius: 8 
                }} 
                formatter={(value) => [`$${(value ?? 0).toLocaleString()}`, "Savings"]} 
              />
              <Bar 
                dataKey="savings" 
                fill="#10b981" 
                radius={[8, 8, 0, 0]} 
              />
            </BarChart>
          </ResponsiveContainer>
        </div>
      </div>

      <ChatBot />
    </AppShell>
  );
}
